/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import KakaoTalk20230822232Image from "../../styles/signup/SignUp_KakaoTalk_20230822_232627325_1.png";
import { styled } from "@mui/material/styles";

const SignUp1 = styled("div")({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle20 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `230px`,
});

const Q = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `247px`,
});

const Q1 = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `700`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `190px`,
  top: `120px`,
});

const Rectangle7 = styled("div")({
  backgroundColor: `rgba(255, 116, 116, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `30px`,
  width: `186px`,
  height: `59px`,
  position: `absolute`,
  left: `507px`,
  top: `911px`,
});

const Rectangle21 = styled("div")({
  backgroundColor: `rgba(255, 116, 116, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `30px`,
  width: `186px`,
  height: `59px`,
  position: `absolute`,
  left: `747px`,
  top: `911px`,
});

const Q2 = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 252, 240, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `600`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `99px`,
  height: `49px`,
  position: `absolute`,
  left: `551px`,
  top: `926px`,
});

const Q3 = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 252, 240, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `600`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `184px`,
  height: `40px`,
  position: `absolute`,
  left: `749px`,
  top: `926px`,
});

const Rectangle22 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `312px`,
});

const Q4 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `329px`,
});

const Rectangle23 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `394px`,
});

const Q5 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `411px`,
});

const Rectangle24 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `476px`,
});

const Rectangle25 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `558px`,
});

const Q6 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `575px`,
});

const Rectangle26 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `640px`,
});

const Q7 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `657px`,
});

const Rectangle27 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `722px`,
});

const Q8 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `739px`,
});

const Rectangle28 = styled("div")({
  backgroundColor: `rgba(255, 252, 240, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `14px`,
  width: `721px`,
  height: `51px`,
  position: `absolute`,
  left: `359px`,
  top: `804px`,
});

const Q9 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `821px`,
});

const Q10 = styled("div")({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nunito`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `150px`,
  position: `absolute`,
  left: `184px`,
  top: `493px`,
});

const KakaoTalk20230822232 = styled("img")({
  height: `150px`,
  width: `150px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `40px`,
  top: `20px`,
});

const Line1 = styled("div")({
  border: `1px solid rgba(180, 28, 71, 1)`,
  width: `1300px`,
  height: `0px`,
  position: `absolute`,
  left: `70px`,
  top: `170px`,
});

function SignUp(props) {
  return (
    <SignUp1 className={props.className}>
      <Rectangle20></Rectangle20>
      <Q>{`아이디`}</Q>
      <Q1>{`홍익대학교 중앙 농구동아리`}</Q1>
      <Rectangle7></Rectangle7>
      <Rectangle21></Rectangle21>
      <Q2>{`취소`}</Q2>
      <Q3>{`회원가입`}</Q3>
      <Rectangle22></Rectangle22>
      <Q4>{`비밀번호`}</Q4>
      <Rectangle23></Rectangle23>
      <Q5>{`비밀번호 확인`}</Q5>
      <Rectangle24></Rectangle24>
      <Rectangle25></Rectangle25>
      <Q6>{`학과`}</Q6>
      <Rectangle26></Rectangle26>
      <Q7>{`학번`}</Q7>
      <Rectangle27></Rectangle27>
      <Q8>{`나이`}</Q8>
      <Rectangle28></Rectangle28>
      <Q9>{`연락처`}</Q9>
      <Q10>{`이름`}</Q10>
      <KakaoTalk20230822232
        src={KakaoTalk20230822232Image}
        loading="lazy"
        alt={"KakaoTalk_20230822_232627325 1"}
      />
      <Line1></Line1>
    </SignUp1>
  );
}

export default SignUp;
